# Generated by Django 5.0.6 on 2026-05-18 17:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок (крупный)')),
                ('subtitle', models.CharField(blank=True, help_text='Пояснение под крупной цифрой', max_length=200, verbose_name='Подпись')),
                ('icon', models.CharField(blank=True, help_text='Например: 🏆, 💼, 🌍', max_length=50, verbose_name='Иконка (emoji или название иконки)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/', verbose_name='Картинка (необязательно)')),
                ('size', models.CharField(choices=[('small', 'Маленькая'), ('medium', 'Средняя'), ('large', 'Большая'), ('wide', 'Широкая')], default='medium', max_length=20, verbose_name='Размер плитки')),
                ('accent', models.BooleanField(default=False, help_text='Выделить плитку золотым акцентом', verbose_name='Золотая подсветка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Плитка достижения',
                'verbose_name_plural': 'Плитки достижений (Bento)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True, verbose_name='Slug (URL)')),
                ('excerpt', models.CharField(blank=True, max_length=500, verbose_name='Анонс (короткое описание)')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Обложка')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Тело статьи')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Статья блога',
                'verbose_name_plural': 'Блог / Статьи',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessTourOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Тур активен')),
                ('start_date', models.DateField(blank=True, help_text='Используется в счётчике и тексте', null=True, verbose_name='Дата старта тура')),
                ('location', models.CharField(default='Дубай', max_length=200, verbose_name='Локация')),
                ('format_text', models.CharField(default='3 дня офлайн + 1 месяц онлайн-сопровождения', max_length=300, verbose_name='Формат')),
                ('deadline', models.DateTimeField(blank=True, help_text='Когда сгорает спец-предложение. Используется в счётчике.', null=True, verbose_name='Дедлайн раннего бронирования')),
                ('bonus_text', models.TextField(blank=True, default='При предоплате 10% сегодня — экспресс-коучинг 1 на 1 с Аллегом в подарок.', verbose_name='Текст бонусного блока')),
            ],
            options={
                'verbose_name': 'Оффер бизнес-тура',
                'verbose_name_plural': 'Оффер бизнес-тура',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Клиент / Компания')),
                ('industry', models.CharField(blank=True, max_length=200, verbose_name='Отрасль/ниша')),
                ('challenge', models.TextField(verbose_name='Задача / точка А')),
                ('result', models.TextField(verbose_name='Результат / точка Б')),
                ('metric_before', models.CharField(blank=True, help_text="Пример: '0,5 млн ₽/мес'", max_length=100, verbose_name="Метрика 'было'")),
                ('metric_after', models.CharField(blank=True, help_text="Пример: '5 млн ₽/мес'", max_length=100, verbose_name="Метрика 'стало'")),
                ('image', models.ImageField(blank=True, null=True, upload_to='cases/', verbose_name='Фото клиента/обложка')),
                ('quote', models.TextField(blank=True, verbose_name='Цитата клиента')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы клиентов',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Вопрос')),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Ответ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'Частые вопросы (FAQ)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text="Например: 'Модуль 1' или '01'", max_length=20, verbose_name='Номер модуля')),
                ('title', models.CharField(max_length=200, verbose_name='Название модуля')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('outcomes', models.TextField(blank=True, help_text='Что получит участник после прохождения', verbose_name='Результаты модуля (каждый с новой строки)')),
                ('duration', models.CharField(blank=True, help_text="Пример: '3 часа' или 'День 1'", max_length=50, verbose_name='Длительность')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Модуль программы',
                'verbose_name_plural': 'Модули программы тура',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Pain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Текст боли')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Боль клиента',
                'verbose_name_plural': "Боли клиентов (блок 'Знакомо?')",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название направления')),
                ('short_description', models.CharField(max_length=300, verbose_name='Короткое описание (одно предложение)')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Полное описание')),
                ('icon', models.CharField(blank=True, help_text='🧠 💼 🚀 🔍 🌍', max_length=50, verbose_name='Иконка/emoji')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Картинка карточки')),
                ('formula', models.CharField(blank=True, help_text="Пример: 'Мышление → Решения → Деньги'", max_length=200, verbose_name='Формула / слоган')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления деятельности',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(default='971500000000', help_text='Пример: 971501234567 — без плюса. Используется во всех CTA-кнопках.', max_length=20, verbose_name='Номер WhatsApp (с кодом страны, без +)')),
                ('whatsapp_prefill', models.TextField(blank=True, default='Здравствуйте, Аллег! Хочу записаться на разбор.', verbose_name='Текст, который автоматически вставится в WhatsApp')),
                ('telegram_username', models.CharField(blank=True, default='alleg_kim', max_length=50, verbose_name='Telegram username (без @)')),
                ('contact_email', models.EmailField(default='info@allegkim.com', max_length=254, verbose_name='Контактный email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон (для отображения)')),
                ('telegram_bot_token', models.CharField(blank=True, help_text='Получить у @BotFather. Используется только для отправки уведомлений о новых заявках.', max_length=200, verbose_name='Токен Telegram-бота для уведомлений')),
                ('telegram_chat_id', models.CharField(blank=True, help_text='ID чата/пользователя/канала, куда отправлять заявки.', max_length=50, verbose_name='Chat ID получателя уведомлений')),
                ('notify_emails', models.CharField(blank=True, default='', help_text='Пример: ceo@allegkim.com, manager@allegkim.com', max_length=500, verbose_name='Email-адреса для дублирующих уведомлений (через запятую)')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='TikTok')),
                ('hero_title', models.CharField(default='Трансформация мышления. Системный масштаб бизнеса.', max_length=300, verbose_name='Заголовок Hero')),
                ('hero_subtitle', models.CharField(default='Международный консалтинг от Аллега Кима', max_length=500, verbose_name='Подзаголовок Hero')),
                ('hero_description', models.TextField(blank=True, default='Ресторатор с 25-летним опытом. Топ-тренер Сюцай Training Institute Dubai. Помогаю предпринимателям перейти на следующий уровень.', verbose_name='Описание под заголовком')),
                ('hero_video_url', models.URLField(blank=True, help_text='Прямая ссылка на видео-файл (можно с Bunny CDN, S3, Mux и т.д.)', verbose_name='Ссылка на фоновое видео (mp4/webm)')),
                ('hero_poster', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Постер для видео / фон Hero')),
                ('hero_primary_cta', models.CharField(default='Записаться на разбор', max_length=100, verbose_name='Текст основной кнопки')),
                ('hero_secondary_cta', models.CharField(default='Узнать о Бизнес-туре', max_length=100, verbose_name='Текст вторичной кнопки')),
                ('about_title', models.CharField(default='Аллег Ким', max_length=200, verbose_name="Заголовок блока 'Обо мне'")),
                ('about_subtitle', models.CharField(blank=True, default='Эксперт, который превращает бизнес в систему', max_length=300, verbose_name='Подзаголовок')),
                ('about_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст о себе')),
                ('about_photo', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name="Фото для блока 'Обо мне'")),
                ('seo_title', models.CharField(default='Аллег Ким — Международный консалтинг и бизнес-тур в Дубае', max_length=200, verbose_name='SEO Title')),
                ('seo_description', models.CharField(default='Трансформация мышления и масштабирование бизнеса. Консалтинг от Аллега Кима, ресторатора с 25-летним опытом.', max_length=300, verbose_name='SEO Description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/', verbose_name='OG-картинка для шеринга')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('price', models.CharField(help_text="Пример: '$5 000' или '2 000 $'", max_length=50, verbose_name='Цена (как отображать)')),
                ('price_note', models.CharField(blank=True, help_text="Пример: 'приведи друга — $1 600'", max_length=200, verbose_name='Подпись к цене')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('features', models.TextField(help_text='Каждый пункт начинай с новой строки. Например:\nДоступ ко всем модулям\n3 дня офлайн\n1 месяц онлайн-поддержки', verbose_name='Что входит (каждая фича — на новой строке)')),
                ('is_highlight', models.BooleanField(default=False, help_text="Подсветить тариф как 'хит'", verbose_name='Хит продаж (выделить)')),
                ('cta_text', models.CharField(default='Выбрать тариф', max_length=100, verbose_name='Текст кнопки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы бизнес-тура',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя автора')),
                ('role', models.CharField(blank=True, max_length=300, verbose_name='Должность / компания')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Фото')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('video_url', models.URLField(blank=True, verbose_name='Видео-отзыв (YouTube/Vimeo)')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Оценка (1-5)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['order'],
            },
        ),
    ]
