# Generated by Django 5.0.6 on 2026-05-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.CharField(blank=True, help_text='Название иконки (lucide). Доступные: award, brain, briefcase, building, chart, check, compass, crown, diamond, flame, gem, globe, graduation, handshake, landmark, line, map, medal, mountain, rocket, search, settings, sparkles, star, target, trending, trophy, users, zap', max_length=50, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text='Название иконки (lucide). Доступные: brain, briefcase, rocket, search, globe, target, compass, chart, trending, sparkles, users, handshake', max_length=50, verbose_name='Иконка'),
        ),
    ]
