# Generated by Django 5.0.6 on 2026-05-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон / WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telegram', models.CharField(blank=True, max_length=200, verbose_name='Telegram / соцсеть')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('source', models.CharField(choices=[('hero', 'Hero / главный CTA'), ('services', 'Блок направлений'), ('tariff', 'Тарифы'), ('business_tour', 'Бизнес-тур'), ('contact_form', 'Контактная форма'), ('popup', 'Поп-ап'), ('footer', 'Подвал'), ('other', 'Другое')], default='contact_form', max_length=30, verbose_name='Источник')),
                ('selected_tariff', models.CharField(blank=True, max_length=100, verbose_name='Выбранный тариф')),
                ('honeypot', models.CharField(blank=True, max_length=200, verbose_name='Honeypot (служебное)')),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('referer', models.CharField(blank=True, max_length=500)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки с сайта',
                'ordering': ['-created_at'],
            },
        ),
    ]
